### ISSUE TITLE
Retrieve the current peak level of a strip

### ISSUE THREAD

**Issue by sanbroz** [SaifAqqad/VMR.ahk#10]
peak_level := Max(voicemeeter.bus[1].level*) is working, but hot to retrieve the current peak level of a strip?

**Comment by Glaived** [comment]
```ahk
peak_level := Max(voicemeeter.strip[1].level*)
```
?

**Comment by sanbroz** [comment]
I already tried peak_level := Max(voicemeeter.strip[1].level*) but it seems not working, can anyone test and report

**Comment by SaifAqqad** [comment]
Seems to be working fine for me



https://user-images.githubusercontent.com/47293197/142770836-be9b8dee-6786-4f5a-bd96-97bb69e500ed.mp4

Post your script so I can help you

**Comment by sanbroz** [comment]
Yes, It worked for first strip only, it is seems not working for other strips and returns -999. Can you please test again with next strips?

![image](https://user-images.githubusercontent.com/562984/142827313-edca6a42-4837-41a8-adfe-a8e47a78cb55.png)

**Comment by SaifAqqad** [comment]
Yep you're right, I will look into it

**Comment by SaifAqqad** [comment]
It turned out to be a bug where all strips (physical and virtual) would take 8 channels instead of 2, so the second and third strips would have their channels in the first strip's `level` array

And all of that happened because I changed the `__isPhysical` method's name a while back without refactoring 🤦🏼‍♂️ 

Commit 3298096 should fix this
