### ISSUE TITLE
`voicemeeter.command.state` causes GetParameterFloat Exception

### ISSUE THREAD

**Issue by ronelm2000** [SaifAqqad/VMR.ahk#8]
...and also doesn't work.
![image](https://user-images.githubusercontent.com/12634987/130550060-99f73981-b0e6-4a6a-b686-5b4b72bbd6f1.png)

All other functionalities for Macro Buttons also do not work.

Using Voicemeeter Potato 3.0.1.8 (x64)

**Comment by SaifAqqad** [comment]
Hey, thank you for reporting this.

I have looked into it and it turned out that all commands are actually write-only 
![image](https://user-images.githubusercontent.com/47293197/130562052-3d0563d3-5a8d-486d-94dd-8bb9d88cd524.png)

So I've removed all calls to `GetParameterFloat` in these command methods.

About the macroButton class, It had a couple of problems:
1. The value of `VBVMR_MacroButton_GetStatus` was being read as an `Int` when it's actually a `Float` 
2. The return value of `MacroButton_GetStatus` was an array of 2 values (the actual value and bitMode for some reason)
3. `setStatus` and `getStatus` had unnecessary and wrong default values for the parameters

It should be all fixed now :D

To _set_ the state of a macrobutton, you can use either 
`voicemeeter.macroButton.setStatus(0,1)`
or
`voicemeeter.command.state(0,1)`

but you can only use `voicemeeter.macroButton.getStatus(0)` to _get_ the state of a macrobutton

and BTW you can toggle the mute state of strip[1] like this `voicemeeter.strip[1].mute := -1`

**Comment by ronelm2000** [comment]
Updates for this:
![image](https://user-images.githubusercontent.com/12634987/130572412-ac0ba5a7-f0b4-4b58-9b67-5881c7f87bd3.png)
![image](https://user-images.githubusercontent.com/12634987/130572673-2a19b43d-0094-48f4-a4c2-632495ed7d4e.png)

This is likely an Voicemeeter Remote API issue tho, as `Command.Button(buttonID).Trigger` doesn't work on Macro Buttons either, but `Button(buttonID).Trigger` does as per User Manual.
![image](https://user-images.githubusercontent.com/12634987/130572552-9fca647b-388e-4e84-88f3-8e41e71ed764.png)

**Comment by SaifAqqad** [comment]
To set the trigger state you can use `setStatus` but you need to pass `3` to bitmode like this
```autohotkey
voicemeeter.macroButton.setStatus(10, 1, 3) ; set button[10] trigger to ON
```
or you can use `command.trigger` like this
```autohotkey
voicemeeter.command.trigger(10, 0) ; set button[10] trigger to OFF
```



Also, command methods will **not** return anything, they just set values
so this will set button[0] state to 1
```autohotkey 
voicemeeter.command.state(0,1)
``` 
but this will not work
```autohotkey
aaaa := voicemeeter.command.state(0)
```

**Comment by SaifAqqad** [comment]
I have updated the [docs](https://saifaqqad.github.io/VMR.ahk/#/VMR-Class/macrobutton-object?id=setstatusbuttonindex-newstatus-bitmode)
